// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spitfy/gofermart/internal/domain/user (interfaces: Storer)

// Package user is a generated GoMock package.
package user

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorer is a mock of Storer interface.
type MockStorer struct {
	ctrl     *gomock.Controller
	recorder *MockStorerMockRecorder
}

// MockStorerMockRecorder is the mock recorder for MockStorer.
type MockStorerMockRecorder struct {
	mock *MockStorer
}

// NewMockStorer creates a new mock instance.
func NewMockStorer(ctrl *gomock.Controller) *MockStorer {
	mock := &MockStorer{ctrl: ctrl}
	mock.recorder = &MockStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorer) EXPECT() *MockStorerMockRecorder {
	return m.recorder
}

// Balance mocks base method.
func (m *MockStorer) Balance(arg0 context.Context, arg1 int) (Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Balance", arg0, arg1)
	ret0, _ := ret[0].(Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Balance indicates an expected call of Balance.
func (mr *MockStorerMockRecorder) Balance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Balance", reflect.TypeOf((*MockStorer)(nil).Balance), arg0, arg1)
}

// PassByLogin mocks base method.
func (m *MockStorer) PassByLogin(arg0 context.Context, arg1 string) (AuthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PassByLogin", arg0, arg1)
	ret0, _ := ret[0].(AuthUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PassByLogin indicates an expected call of PassByLogin.
func (mr *MockStorerMockRecorder) PassByLogin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PassByLogin", reflect.TypeOf((*MockStorer)(nil).PassByLogin), arg0, arg1)
}

// RegisterUser mocks base method.
func (m *MockStorer) RegisterUser(arg0 context.Context, arg1 User) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockStorerMockRecorder) RegisterUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockStorer)(nil).RegisterUser), arg0, arg1)
}

// UserBalance mocks base method.
func (m *MockStorer) UserBalance(arg0 context.Context, arg1 int) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserBalance", arg0, arg1)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserBalance indicates an expected call of UserBalance.
func (mr *MockStorerMockRecorder) UserBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserBalance", reflect.TypeOf((*MockStorer)(nil).UserBalance), arg0, arg1)
}
