// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spitfy/gofermart/internal/domain/order (interfaces: Servicer)

// Package order is a generated GoMock package.
package order

import (
	context "context"
	reflect "reflect"
	sync "sync"

	gomock "github.com/golang/mock/gomock"
	atomic "go.uber.org/atomic"
)

// MockServicer is a mock of Servicer interface.
type MockServicer struct {
	ctrl     *gomock.Controller
	recorder *MockServicerMockRecorder
}

// MockServicerMockRecorder is the mock recorder for MockServicer.
type MockServicerMockRecorder struct {
	mock *MockServicer
}

// NewMockServicer creates a new mock instance.
func NewMockServicer(ctrl *gomock.Controller) *MockServicer {
	mock := &MockServicer{ctrl: ctrl}
	mock.recorder = &MockServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServicer) EXPECT() *MockServicerMockRecorder {
	return m.recorder
}

// AddOrder mocks base method.
func (m *MockServicer) AddOrder(arg0 context.Context, arg1 int, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrder", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrder indicates an expected call of AddOrder.
func (mr *MockServicerMockRecorder) AddOrder(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrder", reflect.TypeOf((*MockServicer)(nil).AddOrder), arg0, arg1, arg2)
}

// ListOrders mocks base method.
func (m *MockServicer) ListOrders(arg0 context.Context, arg1 int) ([]Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", arg0, arg1)
	ret0, _ := ret[0].([]Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockServicerMockRecorder) ListOrders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockServicer)(nil).ListOrders), arg0, arg1)
}

// runSendWorker mocks base method.
func (m *MockServicer) runSendWorker(arg0 context.Context, arg1 *sync.WaitGroup, arg2 atomic.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "runSendWorker", arg0, arg1, arg2)
}

// runSendWorker indicates an expected call of runSendWorker.
func (mr *MockServicerMockRecorder) runSendWorker(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "runSendWorker", reflect.TypeOf((*MockServicer)(nil).runSendWorker), arg0, arg1, arg2)
}
