// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/spitfy/gofermart/internal/domain/order (interfaces: Storer)

// Package order is a generated GoMock package.
package order

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorer is a mock of Storer interface.
type MockStorer struct {
	ctrl     *gomock.Controller
	recorder *MockStorerMockRecorder
}

// MockStorerMockRecorder is the mock recorder for MockStorer.
type MockStorerMockRecorder struct {
	mock *MockStorer
}

// NewMockStorer creates a new mock instance.
func NewMockStorer(ctrl *gomock.Controller) *MockStorer {
	mock := &MockStorer{ctrl: ctrl}
	mock.recorder = &MockStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorer) EXPECT() *MockStorerMockRecorder {
	return m.recorder
}

// addOrder mocks base method.
func (m *MockStorer) addOrder(arg0 context.Context, arg1 Order) (Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "addOrder", arg0, arg1)
	ret0, _ := ret[0].(Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// addOrder indicates an expected call of addOrder.
func (mr *MockStorerMockRecorder) addOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "addOrder", reflect.TypeOf((*MockStorer)(nil).addOrder), arg0, arg1)
}

// listForAccrual mocks base method.
func (m *MockStorer) listForAccrual(arg0 context.Context) ([]orderSend, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "listForAccrual", arg0)
	ret0, _ := ret[0].([]orderSend)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// listForAccrual indicates an expected call of listForAccrual.
func (mr *MockStorerMockRecorder) listForAccrual(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "listForAccrual", reflect.TypeOf((*MockStorer)(nil).listForAccrual), arg0)
}

// listOrders mocks base method.
func (m *MockStorer) listOrders(arg0 context.Context, arg1 int) ([]Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "listOrders", arg0, arg1)
	ret0, _ := ret[0].([]Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// listOrders indicates an expected call of listOrders.
func (mr *MockStorerMockRecorder) listOrders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "listOrders", reflect.TypeOf((*MockStorer)(nil).listOrders), arg0, arg1)
}
